<div class="twoCols-84">
	<div class="col-1 main">
		<h1>Contact us Today!</h1>
		<p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Sed ac sagittis lorem, malesuada pharetra ipsum. Praesent efficitur mi vel molestie gravida. Mauris interdum, neque quis interdum rhoncus, nulla augue varius diam, ac sagittis tortor augue vitae eros. Nulla facilisi. Mauris scelerisque est ut pellentesque euismod. Cras eget mollis nisl. In a augue gravida, scelerisque tellus at, blandit velit. Nunc nulla felis, dictum vel eros a, consequat pharetra nisl. In commodo ipsum ut tellus tincidunt, ut consectetur turpis dapibus.Lorem ipsum dolor sit amet, consectetur adipiscing elit. Sed ac sagittis lorem, malesuada pharetra ipsum. Praesent efficitur mi vel molestie gravida. Mauris interdum, neque quis interdum rhoncus, nulla augue varius diam, ac sagittis tortor augue vitae eros. Nulla facilisi. Mauris scelerisque est ut pellentesque euismod. Cras eget mollis nisl. In a augue gravida, scelerisque tellus at, blandit velit. Nunc nulla felis, dictum vel eros a, consequat pharetra nisl. In commodo ipsum ut tellus tincidunt, ut consectetur turpis dapibus.</p>
		<p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Sed ac sagittis lorem, malesuada pharetra ipsum. Praesent efficitur mi vel molestie gravida. Mauris interdum, neque quis interdum rhoncus, nulla augue varius diam, ac sagittis tortor augue vitae eros. Nulla facilisi. Mauris scelerisque est ut pellentesque euismod. Cras eget mollis nisl. In a augue gravida, scelerisque tellus at, blandit velit. Nunc nulla felis, dictum vel eros a, consequat pharetra nisl. In commodo ipsum ut tellus tincidunt, ut consectetur turpis dapibus.Lorem ipsum dolor sit amet, consectetur adipiscing elit. Sed ac sagittis lorem, malesuada pharetra ipsum. Praesent efficitur mi vel molestie gravida. Mauris interdum, neque quis interdum rhoncus, nulla augue varius diam, ac sagittis tortor augue vitae eros. Nulla facilisi. Mauris scelerisque est ut pellentesque euismod. Cras eget mollis nisl. In a augue gravida, scelerisque tellus at, blandit velit. Nunc nulla felis, dictum vel eros a, consequat pharetra nisl. In commodo ipsum ut tellus tincidunt, ut consectetur turpis dapibus.</p>
	</div>
	<div class="col-2 info">
		<div>
			<p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Sed ac sagittis lorem, malesuada pharetra ipsum. Praesent efficitur mi vel molestie gravida. Mauris interdum, neque quis interdum rhoncus, nulla augue varius diam, ac sagittis tortor augue vitae eros. Nulla facilisi. Mauris scelerisque est ut pellentesque euismod. Cras eget mollis nisl. In a augue gravida, scelerisque tellus at, blandit velit. Nunc nulla felis, dictum vel eros a, consequat pharetra nisl. In commodo ipsum ut tellus tincidunt, ut consectetur turpis dapibus.</p>
		</div>
		<div>
			<p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Sed ac sagittis lorem, malesuada pharetra ipsum. Praesent efficitur mi vel molestie gravida. Mauris interdum, neque quis interdum rhoncus, nulla augue varius diam, ac sagittis tortor augue vitae eros. Nulla facilisi. Mauris scelerisque est ut pellentesque euismod. Cras eget mollis nisl. In a augue gravida, scelerisque tellus at, blandit velit. Nunc nulla felis, dictum vel eros a, consequat pharetra nisl. In commodo ipsum ut tellus tincidunt, ut consectetur turpis dapibus.</p>
		</div>
		<div>
			<p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Sed ac sagittis lorem, malesuada pharetra ipsum. Praesent efficitur mi vel molestie gravida. Mauris interdum, neque quis interdum rhoncus, nulla augue varius diam, ac sagittis tortor augue vitae eros. Nulla facilisi. Mauris scelerisque est ut pellentesque euismod. Cras eget mollis nisl. In a augue gravida, scelerisque tellus at, blandit velit. Nunc nulla felis, dictum vel eros a, consequat pharetra nisl. In commodo ipsum ut tellus tincidunt, ut consectetur turpis dapibus.</p>
		</div>
	</div>
</div>