<div>
	<form class="forms">
		<div class="input-group">
			<input type="text" name="firstName">
			<label>First Name</label>
		</div>

		<div class="input-group">
			<input type="text" name="lastName">
			<label>Last Name</label>
		</div>

		<div class="input-group">
			<input type="email" name="email">
			<label>Your Email</label>
		</div>

		<div class="input-group">
			<input type="text" name="phone">
			<label>Your Phone #</label>
		</div>

		<div class="input-group">
			<input type="text" name="address">
			<label>Your Street Address</label>
		</div>

		<input type="submit" name="Submit" value="Continue">
	</form>
</div>